# syntax=docker/dockerfile:1

FROM golang:1.22-alpine AS build
WORKDIR /src
RUN apk add --no-cache git ca-certificates
ENV GOCACHE=/tmp/go-cache
ENV GOMODCACHE=/tmp/go-mod

ARG SERVICE

COPY packages/go-common ./packages/go-common
COPY packages/events ./packages/events
COPY services/${SERVICE} ./services/${SERVICE}

WORKDIR /src/services/${SERVICE}
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /out/service ./cmd

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata && \
    adduser -D -H -u 10001 jp
WORKDIR /app
COPY --from=build /out/service /app/service
ARG SERVICE
COPY services/${SERVICE}/migrations /app/migrations
ENV MIGRATIONS_DIR=/app/migrations
USER jp
ENTRYPOINT ["/app/service"]
