#!/usr/bin/env bash
# Detects host RAM/CPU and writes .env.resources for adaptive jp sizing.
# Usage: ./scripts/size-host.sh [auto|small|medium|large|xlarge]
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
FORCED="${1:-auto}"

ram_gb() {
  if [[ -f /proc/meminfo ]]; then
    awk '/MemTotal/ {printf "%.1f", $2/1024/1024}' /proc/meminfo
  elif command -v sysctl >/dev/null 2>&1; then
    # macOS
    python3 -c "import os; print(round(os.sysconf('SC_PAGE_SIZE')*os.sysconf('SC_PHYS_PAGES')/1024**3,1))" 2>/dev/null || echo 8.0
  else
    echo 8.0
  fi
}

cpus() {
  if command -v nproc >/dev/null 2>&1; then nproc
  elif [[ -f /proc/cpuinfo ]]; then grep -c ^processor /proc/cpuinfo
  else echo 4
  fi
}

RAM="$(ram_gb)"
CPUS="$(cpus)"

tier_from_ram() {
  local r="$1"
  awk -v r="$r" 'BEGIN {
    if (r < 6) print "small";
    else if (r < 16) print "medium";
    else if (r < 32) print "large";
    else print "xlarge";
  }'
}

if [[ "$FORCED" != "auto" ]]; then
  TIER="$FORCED"
else
  TIER="$(tier_from_ram "$RAM")"
fi

case "$TIER" in
  small)  REPLICAS=1; CONC=1; BUILD=simulate; RUNTIME=simulate; METRICS=simulate; SUGGESTED=platform ;;
  medium) REPLICAS=2; CONC=2; BUILD=docker; RUNTIME=docker; METRICS=live; SUGGESTED=platform,ui,data ;;
  large)  REPLICAS=4; CONC=2; BUILD=docker; RUNTIME=docker; METRICS=live; SUGGESTED=platform,ui,data,monitoring ;;
  xlarge) REPLICAS=8; CONC=4; BUILD=docker; RUNTIME=docker; METRICS=live; SUGGESTED=platform,ui,data,monitoring,dev ;;
  *) echo "unknown tier: $TIER" >&2; exit 1 ;;
esac

SIMULATE=false
[[ "$BUILD" == "simulate" ]] && SIMULATE=true

OVERLAY="infra/compose/sizing/${TIER}.yml"
OUT="$ROOT/.env.resources"

cat > "$OUT" <<EOF
# Generated by scripts/size-host.sh — do not commit secrets here.
# Host: ${RAM} GB RAM, ${CPUS} logical CPUs → JP_SIZE=$TIER
JP_SIZE=$TIER
JP_HOST_RAM_GB=$RAM
JP_HOST_CPUS=$CPUS
WORKER_REPLICAS=$REPLICAS
WORKER_CONCURRENCY=$CONC
COMPOSE_SIZING_FILE=$OVERLAY
JP_SUGGESTED_PROFILES=$SUGGESTED
BUILD_MODE=$BUILD
SIMULATE_BUILD=$SIMULATE
RUNTIME_MODE=$RUNTIME
METRICS_MODE=$METRICS
EOF

echo "jp sizing: $TIER (${RAM} GB RAM, ${CPUS} CPUs)"
echo "  workers × $REPLICAS  concurrency/worker=$CONC"
echo "  overlay: $OVERLAY"
echo "  suggested profiles: $SUGGESTED"
echo "  wrote: $OUT"
echo ""
echo "Next: ./scripts/jp-up.sh"
