# Detects host RAM/CPU and writes .env.resources for adaptive jp sizing.
# Usage: .\scripts\size-host.ps1 [-Size small|medium|large|xlarge|auto]

param(
    [ValidateSet("auto", "small", "medium", "large", "xlarge")]
    [string]$Size = "auto"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Get-HostRamGB {
    try {
        $bytes = (Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory
        return [math]::Round($bytes / 1GB, 1)
    } catch {
        return 8.0
    }
}

function Get-HostCpus {
    try {
        return [int](Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
    } catch {
        return 4
    }
}

function Resolve-Tier([double]$RamGB, [string]$Forced) {
    if ($Forced -ne "auto") { return $Forced }
    if ($RamGB -lt 6) { return "small" }
    if ($RamGB -lt 16) { return "medium" }
    if ($RamGB -lt 32) { return "large" }
    return "xlarge"
}

$ram = Get-HostRamGB
$cpus = Get-HostCpus
$tier = Resolve-Tier $ram $Size

$replicas = switch ($tier) {
    "small"  { 1 }
    "medium" { 2 }
    "large"  { 4 }
    "xlarge" { 8 }
}
$concurrency = switch ($tier) {
    "small"  { 1 }
    "medium" { 2 }
    "large"  { 2 }
    "xlarge" { 4 }
}

# Prefer real docker builds on medium+ when not explicitly set later
# small still defaults to simulate for tiny VPS demos; use scripts/go-real.* to force docker everywhere
$buildMode = if ($tier -eq "small") { "simulate" } else { "docker" }
$runtimeMode = if ($tier -eq "small") { "simulate" } else { "docker" }
$metricsMode = if ($tier -eq "small") { "simulate" } else { "live" }

$suggested = switch ($tier) {
    "small"  { "platform" }
    "medium" { "platform,ui,data" }
    "large"  { "platform,ui,data,monitoring" }
    "xlarge" { "platform,ui,data,monitoring,dev" }
}

$overlay = "infra/compose/sizing/$tier.yml"
$out = Join-Path $Root ".env.resources"

@"
# Generated by scripts/size-host.ps1 — do not commit secrets here.
# Host: ${ram} GB RAM, ${cpus} logical CPUs → JP_SIZE=$tier
JP_SIZE=$tier
JP_HOST_RAM_GB=$ram
JP_HOST_CPUS=$cpus
WORKER_REPLICAS=$replicas
WORKER_CONCURRENCY=$concurrency
COMPOSE_SIZING_FILE=$overlay
JP_SUGGESTED_PROFILES=$suggested
# Soft defaults for this tier (override in .env if you want)
BUILD_MODE=$buildMode
SIMULATE_BUILD=$($buildMode -eq "simulate")
RUNTIME_MODE=$runtimeMode
METRICS_MODE=$metricsMode
"@ | Set-Content -Path $out -Encoding utf8

Write-Host "jp sizing: $tier (${ram} GB RAM, $cpus CPUs)"
Write-Host "  workers × $replicas  concurrency/worker=$concurrency"
Write-Host "  overlay: $overlay"
Write-Host "  suggested profiles: $suggested"
Write-Host "  wrote: $out"
Write-Host ""
Write-Host "Next: .\scripts\jp-up.ps1"
